version: 1.0.{build}
image: Visual Studio 2017
platform: x64
configuration: Release

before_build:
    - git submodule update --init --recursive
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - mkdir build

build_script:
    - cd build
    - cmake -A %PLATFORM% ..
    - cmake --build . --config %CONFIGURATION%

test_script:
    - ctest . -C %CONFIGURATION%

