dist: trusty
language: cpp
sudo: false

git:
    depth: 5

cache:
    apt: true

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - mkdir build

script:
    - cd build
    - cmake ..
    - cmake --build .
    - ctest

addons:
    apt:
        sources: &global_apt_sources
            - ubuntu-toolchain-r-test
        packages: &global_apt_packages
            - cmake3
            - libdw-dev

matrix:
    include:
        - os: linux
          compiler: gcc
          env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
          addons:
              apt:
                  sources:
                      - *global_apt_sources
                  packages:
                      - *global_apt_packages
                      - g++-7
        - os: linux
          compiler: clang
          env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
          addons:
              apt:
                  sources:
                      - *global_apt_sources
                      - llvm-toolchain-trusty-5.0
                  packages:
                      - *global_apt_packages
                      - clang-5.0
        - os: osx
          osx_image: xcode9
